angular.module('hextechhuntClientApp')
  .service('CanvasLoaderService', function() {
    // Lines 4-15 have been generated by the CanvasLoader Creator (http://heartcode.robertpataki.com/canvasloader/)
    var canvasLoader = new CanvasLoader('canvasloader-container');
    canvasLoader.setColor('#1D2C8B');
    canvasLoader.setShape('square');
    canvasLoader.setDiameter(150);
    canvasLoader.setDensity(80);
    canvasLoader.setRange(1);
    canvasLoader.setFPS(30);

    var loaderObject = document.getElementById("canvasLoader");
    loaderObject.style.position = "absolute";
    loaderObject.style["top"] = canvasLoader.getDiameter() * -0.5 + "px";
    loaderObject.style["left"] = canvasLoader.getDiameter() * -0.5 + "px";

    // Hide the current view and display the CanvasLoader
    this.showSpinner = function() {
      $('#view-container').hide();
      canvasLoader.show();
    };

    // Hide the CanvasLoader and display the current view
    this.hideSpinner = function() {
      canvasLoader.hide();
      $('#view-container').hide().fadeIn(500);
    };
  });
